name: so_argo_minimal
channels:
  - conda-forge
dependencies:
  - python=3.8.17
  - cartopy=0.21.1
  - conda-lock=2.5.6
  - gsw=3.6.17
  - jupyterlab=3.6.3
  - matplotlib=3.7.1
  - numpy=1.24.3
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - scipy=1.9.3
  - seaborn=0.12.2
  - tqdm=4.65.0
  - xarray=2022.11.0

